version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./Backend/Dockerfile
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      - database
    networks:
      custom_network:
        ipv4_address: 172.28.1.2

  frontend:
    build:
      context: .
      dockerfile: ./Frontend/Dockerfile
    ports:
      - "80:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      - backend
    networks:
      custom_network:
        ipv4_address: 172.28.1.3

  database:
    image: postgres:14.3
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      custom_network:
        ipv4_address: 172.28.1.4

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

# Las variables de entorno estás definidas en el fichero .env.local
# se debe copiar a un fichero .env en la misma ruta para que lo evalue
# el docker-compose

# comand to start up
# docker-compose up --build