version: '3'

services:
  backend:
    build:
      context: ./Backend
    ports:
      - "${API_PORT}:80"

  frontend:
    build:
      context: ./Frontend
    ports:
      - "${WEB_PORT}:80"
  database:
    image: postgres:14.3
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres


# Las variables de entorno estás definidas en el fichero .env.local
# se debe copiar a un fichero .env en la misma ruta para que lo evalue
# el docker-compose

# comand to start up
# docker-compose --env-file ./.env.local up --build