version: '3'

services:
  backend:
    build:
      context: ./Backend
    ports:
      - "${API_PORT}:80"

  frontend:
    build:
      context: ./Frontend
    ports:
      - "${WEB_PORT}:80"

# comand to start up
# docker-compose --env-file ./.env.local up --build