// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240330115431_products")]
    partial class products
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartTrade.Models.Gallery", b =>
                {
                    b.Property<int>("Product_code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Product_code"));

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.HasKey("Product_code");

                    b.ToTable("Gallery");
                });

            modelBuilder.Entity("SmartTrade.Models.GroceryProduct", b =>
                {
                    b.Property<int>("Product_code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Product_code"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Features")
                        .HasColumnType("text");

                    b.Property<int>("Huella")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Product_code");

                    b.ToTable("GroceryProduct");

                    b.HasData(
                        new
                        {
                            Product_code = 6,
                            Category = "Grocerie",
                            Description = "descripci�n6",
                            Features = "caracter�sticas6",
                            Huella = 10,
                            Name = "product6",
                            Price = 16f
                        },
                        new
                        {
                            Product_code = 7,
                            Category = "Grocerie",
                            Description = "descripci�n7",
                            Features = "caracter�sticas7",
                            Huella = 13,
                            Name = "product7",
                            Price = 17f
                        },
                        new
                        {
                            Product_code = 8,
                            Category = "Grocerie",
                            Description = "descripci�n8",
                            Features = "caracter�sticas8",
                            Huella = -9,
                            Name = "product8",
                            Price = 18f
                        },
                        new
                        {
                            Product_code = 9,
                            Category = "Grocerie",
                            Description = "descripci�n9",
                            Features = "caracter�sticas9",
                            Huella = -16,
                            Name = "product9",
                            Price = 19f
                        },
                        new
                        {
                            Product_code = 10,
                            Category = "Grocerie",
                            Description = "descripci�n10",
                            Features = "caracter�sticas10",
                            Huella = -3,
                            Name = "product10",
                            Price = 20f
                        },
                        new
                        {
                            Product_code = 11,
                            Category = "Grocerie",
                            Description = "descripci�n11",
                            Features = "caracter�sticas11",
                            Huella = 24,
                            Name = "product11",
                            Price = 21f
                        },
                        new
                        {
                            Product_code = 12,
                            Category = "Grocerie",
                            Description = "descripci�n12",
                            Features = "caracter�sticas12",
                            Huella = 37,
                            Name = "product12",
                            Price = 22f
                        },
                        new
                        {
                            Product_code = 13,
                            Category = "Grocerie",
                            Description = "descripci�n13",
                            Features = "caracter�sticas13",
                            Huella = 45,
                            Name = "product13",
                            Price = 23f
                        },
                        new
                        {
                            Product_code = 14,
                            Category = "Grocerie",
                            Description = "descripci�n14",
                            Features = "caracter�sticas14",
                            Huella = 39,
                            Name = "product14",
                            Price = 24f
                        },
                        new
                        {
                            Product_code = 15,
                            Category = "Grocerie",
                            Description = "descripci�n15",
                            Features = "caracter�sticas15",
                            Huella = 5,
                            Name = "product15",
                            Price = 25f
                        });
                });

            modelBuilder.Entity("SmartTrade.Models.SportProduct", b =>
                {
                    b.Property<int>("Product_code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Product_code"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Features")
                        .HasColumnType("text");

                    b.Property<int>("Huella")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Product_code");

                    b.ToTable("SportProduct");

                    b.HasData(
                        new
                        {
                            Product_code = 1,
                            Category = "Sports",
                            Description = "descripci�n1",
                            Features = "caracter�sticas1",
                            Huella = 21,
                            Name = "product1",
                            Price = 11f
                        },
                        new
                        {
                            Product_code = 2,
                            Category = "Sports",
                            Description = "descripci�n2",
                            Features = "caracter�sticas2",
                            Huella = 52,
                            Name = "product2",
                            Price = 12f
                        },
                        new
                        {
                            Product_code = 3,
                            Category = "Sports",
                            Description = "descripci�n3",
                            Features = "caracter�sticas3",
                            Huella = 26,
                            Name = "product3",
                            Price = 13f
                        },
                        new
                        {
                            Product_code = 4,
                            Category = "Sports",
                            Description = "descripci�n4",
                            Features = "caracter�sticas4",
                            Huella = 19,
                            Name = "product4",
                            Price = 14f
                        },
                        new
                        {
                            Product_code = 5,
                            Category = "Sports",
                            Description = "descripci�n5",
                            Features = "caracter�sticas5",
                            Huella = -5,
                            Name = "product5",
                            Price = 15f
                        });
                });

            modelBuilder.Entity("SmartTrade.Models.TechnoProduct", b =>
                {
                    b.Property<int>("Product_code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Product_code"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Features")
                        .HasColumnType("text");

                    b.Property<int>("Huella")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Product_code");

                    b.ToTable("TechnoProduct");

                    b.HasData(
                        new
                        {
                            Product_code = 11,
                            Category = "Techno",
                            Description = "descripci�n11",
                            Features = "caracter�sticas11",
                            Huella = 18,
                            Name = "product11",
                            Price = 21f
                        },
                        new
                        {
                            Product_code = 12,
                            Category = "Techno",
                            Description = "descripci�n12",
                            Features = "caracter�sticas12",
                            Huella = 43,
                            Name = "product12",
                            Price = 22f
                        },
                        new
                        {
                            Product_code = 13,
                            Category = "Techno",
                            Description = "descripci�n13",
                            Features = "caracter�sticas13",
                            Huella = -4,
                            Name = "product13",
                            Price = 23f
                        },
                        new
                        {
                            Product_code = 14,
                            Category = "Techno",
                            Description = "descripci�n14",
                            Features = "caracter�sticas14",
                            Huella = 5,
                            Name = "product14",
                            Price = 24f
                        },
                        new
                        {
                            Product_code = 15,
                            Category = "Techno",
                            Description = "descripci�n15",
                            Features = "caracter�sticas15",
                            Huella = -17,
                            Name = "product15",
                            Price = 25f
                        },
                        new
                        {
                            Product_code = 16,
                            Category = "Techno",
                            Description = "descripci�n16",
                            Features = "caracter�sticas16",
                            Huella = 35,
                            Name = "product16",
                            Price = 26f
                        },
                        new
                        {
                            Product_code = 17,
                            Category = "Techno",
                            Description = "descripci�n17",
                            Features = "caracter�sticas17",
                            Huella = 13,
                            Name = "product17",
                            Price = 27f
                        },
                        new
                        {
                            Product_code = 18,
                            Category = "Techno",
                            Description = "descripci�n18",
                            Features = "caracter�sticas18",
                            Huella = 8,
                            Name = "product18",
                            Price = 28f
                        },
                        new
                        {
                            Product_code = 19,
                            Category = "Techno",
                            Description = "descripci�n19",
                            Features = "caracter�sticas19",
                            Huella = 6,
                            Name = "product19",
                            Price = 29f
                        },
                        new
                        {
                            Product_code = 20,
                            Category = "Techno",
                            Description = "descripci�n20",
                            Features = "caracter�sticas20",
                            Huella = 12,
                            Name = "product20",
                            Price = 30f
                        },
                        new
                        {
                            Product_code = 21,
                            Category = "Techno",
                            Description = "descripci�n21",
                            Features = "caracter�sticas21",
                            Huella = 38,
                            Name = "product21",
                            Price = 31f
                        },
                        new
                        {
                            Product_code = 22,
                            Category = "Techno",
                            Description = "descripci�n22",
                            Features = "caracter�sticas22",
                            Huella = -15,
                            Name = "product22",
                            Price = 32f
                        },
                        new
                        {
                            Product_code = 23,
                            Category = "Techno",
                            Description = "descripci�n23",
                            Features = "caracter�sticas23",
                            Huella = -12,
                            Name = "product23",
                            Price = 33f
                        },
                        new
                        {
                            Product_code = 24,
                            Category = "Techno",
                            Description = "descripci�n24",
                            Features = "caracter�sticas24",
                            Huella = 2,
                            Name = "product24",
                            Price = 34f
                        },
                        new
                        {
                            Product_code = 25,
                            Category = "Techno",
                            Description = "descripci�n25",
                            Features = "caracter�sticas25",
                            Huella = 4,
                            Name = "product25",
                            Price = 35f
                        });
                });

            modelBuilder.Entity("SmartTrade.Models.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 3, 31, 11, 54, 31, 379, DateTimeKind.Utc).AddTicks(2754),
                            TemperatureC = 53
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 4, 1, 11, 54, 31, 379, DateTimeKind.Utc).AddTicks(2787),
                            TemperatureC = -19
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 4, 2, 11, 54, 31, 379, DateTimeKind.Utc).AddTicks(2802),
                            TemperatureC = -18
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2024, 4, 3, 11, 54, 31, 379, DateTimeKind.Utc).AddTicks(2811),
                            TemperatureC = 30
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2024, 4, 4, 11, 54, 31, 379, DateTimeKind.Utc).AddTicks(2825),
                            TemperatureC = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
