// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240522170011_productosDescriptivos")]
    partial class productosDescriptivos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Database.GalleryEntity", b =>
                {
                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<int?>("Category")
                        .HasColumnType("integer");

                    b.Property<int?>("Product_code")
                        .HasColumnType("integer");

                    b.HasKey("Image");

                    b.HasIndex("Product_code");

                    b.ToTable("Gallery");

                    b.HasData(
                        new
                        {
                            Image = "https://i.imgur.com/WtfQOF3.png",
                            Product_code = 1
                        },
                        new
                        {
                            Image = "https://i.imgur.com/bRFgYfL.png",
                            Product_code = 2
                        },
                        new
                        {
                            Image = "https://i.imgur.com/0kTxfNT.png",
                            Product_code = 3
                        },
                        new
                        {
                            Image = "https://i.imgur.com/tewVKu5.png",
                            Product_code = 4
                        },
                        new
                        {
                            Image = "https://i.imgur.com/VcVlhzr.png",
                            Product_code = 5
                        },
                        new
                        {
                            Image = "https://i.imgur.com/9ZpZZfe.png",
                            Product_code = 6
                        },
                        new
                        {
                            Image = "https://i.imgur.com/YgKapTz.png",
                            Product_code = 7
                        },
                        new
                        {
                            Image = "https://i.imgur.com/kgj7C77.png",
                            Product_code = 8
                        },
                        new
                        {
                            Image = "https://i.imgur.com/ATQsdPb.png",
                            Product_code = 9
                        },
                        new
                        {
                            Image = "https://i.imgur.com/ADMjfOX.png",
                            Product_code = 10
                        },
                        new
                        {
                            Image = "https://i.imgur.com/IMMlRaG.png",
                            Product_code = 11
                        },
                        new
                        {
                            Image = "https://i.imgur.com/qNLCqrT.png",
                            Product_code = 12
                        },
                        new
                        {
                            Image = "https://i.imgur.com/qImnFwc.png",
                            Product_code = 13
                        },
                        new
                        {
                            Image = "https://i.imgur.com/icpDfTu.png",
                            Product_code = 14
                        },
                        new
                        {
                            Image = "https://i.imgur.com/B9UeUnE.png",
                            Product_code = 15
                        },
                        new
                        {
                            Image = "https://www.timeshighereducation.com/student/sites/default/files/styles/default/public/different_sports.jpg",
                            Category = 2
                        },
                        new
                        {
                            Image = "https://hips.hearstapps.com/hmg-prod/images/online-buying-and-delivery-concept-royalty-free-image-1675370119.jpg",
                            Category = 1
                        },
                        new
                        {
                            Image = "https://miro.medium.com/v2/resize:fit:720/format:webp/1*f9N5gbBNXLGqD7NgjzVg5g.jpeg",
                            Category = 0
                        });
                });

            modelBuilder.Entity("Backend.Database.ListEntity", b =>
                {
                    b.Property<int>("List_code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("List_code"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("List_code");

                    b.ToTable("List");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ListEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Backend.Database.ListProduct", b =>
                {
                    b.Property<int>("Product_code")
                        .HasColumnType("integer");

                    b.Property<int>("List_code")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Product_code", "List_code");

                    b.HasIndex("List_code");

                    b.ToTable("ListProducts");

                    b.HasData(
                        new
                        {
                            Product_code = 11,
                            List_code = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Product_code = 12,
                            List_code = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Product_code = 13,
                            List_code = 3,
                            Quantity = 1
                        },
                        new
                        {
                            Product_code = 14,
                            List_code = 4,
                            Quantity = 1
                        },
                        new
                        {
                            Product_code = 15,
                            List_code = 5,
                            Quantity = 1
                        },
                        new
                        {
                            Product_code = 6,
                            List_code = 6,
                            Quantity = 1
                        },
                        new
                        {
                            Product_code = 7,
                            List_code = 7,
                            Quantity = 1
                        },
                        new
                        {
                            Product_code = 8,
                            List_code = 8,
                            Quantity = 1
                        },
                        new
                        {
                            Product_code = 9,
                            List_code = 9,
                            Quantity = 1
                        },
                        new
                        {
                            Product_code = 10,
                            List_code = 10,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("Backend.Database.PersonEntity", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("integer");

                    b.HasKey("Email");

                    b.ToTable("Person");

                    b.HasDiscriminator<string>("Discriminator").HasValue("PersonEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Backend.Database.ProductEntity", b =>
                {
                    b.Property<int>("Product_code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Product_code"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Features")
                        .HasColumnType("text");

                    b.Property<int>("FingerPrint")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Product_code");

                    b.ToTable("Products");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ProductEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Backend.Database.GiftListEntity", b =>
                {
                    b.HasBaseType("Backend.Database.ListEntity");

                    b.Property<string>("ClientEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("ClientEmail")
                        .IsUnique();

                    b.ToTable("List", t =>
                        {
                            t.Property("ClientEmail")
                                .HasColumnName("GiftListEntity_ClientEmail");
                        });

                    b.HasDiscriminator().HasValue("GiftListEntity");

                    b.HasData(
                        new
                        {
                            List_code = 6,
                            Name = "GiftList",
                            ClientEmail = "prueba1@prueba.com"
                        },
                        new
                        {
                            List_code = 7,
                            Name = "GiftList",
                            ClientEmail = "prueba2@prueba.com"
                        },
                        new
                        {
                            List_code = 8,
                            Name = "GiftList",
                            ClientEmail = "prueba3@prueba.com"
                        },
                        new
                        {
                            List_code = 9,
                            Name = "GiftList",
                            ClientEmail = "prueba4@prueba.com"
                        },
                        new
                        {
                            List_code = 10,
                            Name = "GiftList",
                            ClientEmail = "prueba5@prueba.com"
                        });
                });

            modelBuilder.Entity("Backend.Database.LaterListEntity", b =>
                {
                    b.HasBaseType("Backend.Database.ListEntity");

                    b.Property<string>("ClientEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("ClientEmail")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("LaterListEntity");

                    b.HasData(
                        new
                        {
                            List_code = 16,
                            Name = "LaterList",
                            ClientEmail = "prueba1@prueba.com"
                        },
                        new
                        {
                            List_code = 17,
                            Name = "LaterList",
                            ClientEmail = "prueba2@prueba.com"
                        },
                        new
                        {
                            List_code = 18,
                            Name = "LaterList",
                            ClientEmail = "prueba3@prueba.com"
                        },
                        new
                        {
                            List_code = 19,
                            Name = "LaterList",
                            ClientEmail = "prueba4@prueba.com"
                        },
                        new
                        {
                            List_code = 20,
                            Name = "LaterList",
                            ClientEmail = "prueba5@prueba.com"
                        });
                });

            modelBuilder.Entity("Backend.Database.ShoppingCartEntity", b =>
                {
                    b.HasBaseType("Backend.Database.ListEntity");

                    b.Property<string>("ClientEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("ClientEmail")
                        .IsUnique();

                    b.ToTable("List", t =>
                        {
                            t.Property("ClientEmail")
                                .HasColumnName("ShoppingCartEntity_ClientEmail");
                        });

                    b.HasDiscriminator().HasValue("ShoppingCartEntity");

                    b.HasData(
                        new
                        {
                            List_code = 11,
                            Name = "ShoppingCart",
                            ClientEmail = "prueba1@prueba.com"
                        },
                        new
                        {
                            List_code = 12,
                            Name = "ShoppingCart",
                            ClientEmail = "prueba2@prueba.com"
                        },
                        new
                        {
                            List_code = 13,
                            Name = "ShoppingCart",
                            ClientEmail = "prueba3@prueba.com"
                        },
                        new
                        {
                            List_code = 14,
                            Name = "ShoppingCart",
                            ClientEmail = "prueba4@prueba.com"
                        },
                        new
                        {
                            List_code = 15,
                            Name = "ShoppingCart",
                            ClientEmail = "prueba5@prueba.com"
                        });
                });

            modelBuilder.Entity("Backend.Database.WishListEntity", b =>
                {
                    b.HasBaseType("Backend.Database.ListEntity");

                    b.Property<string>("ClientEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("ClientEmail")
                        .IsUnique();

                    b.ToTable("List", t =>
                        {
                            t.Property("ClientEmail")
                                .HasColumnName("WishListEntity_ClientEmail");
                        });

                    b.HasDiscriminator().HasValue("WishListEntity");

                    b.HasData(
                        new
                        {
                            List_code = 1,
                            Name = "WishList",
                            ClientEmail = "prueba1@prueba.com"
                        },
                        new
                        {
                            List_code = 2,
                            Name = "WishList",
                            ClientEmail = "prueba2@prueba.com"
                        },
                        new
                        {
                            List_code = 3,
                            Name = "WishList",
                            ClientEmail = "prueba3@prueba.com"
                        },
                        new
                        {
                            List_code = 4,
                            Name = "WishList",
                            ClientEmail = "prueba4@prueba.com"
                        },
                        new
                        {
                            List_code = 5,
                            Name = "WishList",
                            ClientEmail = "prueba5@prueba.com"
                        });
                });

            modelBuilder.Entity("Backend.Database.ClientEntity", b =>
                {
                    b.HasBaseType("Backend.Database.PersonEntity");

                    b.HasDiscriminator().HasValue("ClientEntity");

                    b.HasData(
                        new
                        {
                            Email = "prueba1@prueba.com",
                            FullName = "Cliente 1",
                            Password = "cliente1",
                            PhoneNumber = 654654655
                        },
                        new
                        {
                            Email = "prueba2@prueba.com",
                            FullName = "Cliente 2",
                            Password = "cliente2",
                            PhoneNumber = 654654656
                        },
                        new
                        {
                            Email = "prueba3@prueba.com",
                            FullName = "Cliente 3",
                            Password = "cliente3",
                            PhoneNumber = 654654657
                        },
                        new
                        {
                            Email = "prueba4@prueba.com",
                            FullName = "Cliente 4",
                            Password = "cliente4",
                            PhoneNumber = 654654658
                        },
                        new
                        {
                            Email = "prueba5@prueba.com",
                            FullName = "Cliente 5",
                            Password = "cliente5",
                            PhoneNumber = 654654659
                        });
                });

            modelBuilder.Entity("Backend.Database.SalesPersonEntity", b =>
                {
                    b.HasBaseType("Backend.Database.PersonEntity");

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("SalesPersonEntity");
                });

            modelBuilder.Entity("Backend.Database.GroceryProductEntity", b =>
                {
                    b.HasBaseType("Backend.Database.ProductEntity");

                    b.HasDiscriminator().HasValue("GroceryProductEntity");

                    b.HasData(
                        new
                        {
                            Product_code = 6,
                            Category = 1,
                            Description = "Tomate de rama de gran calidad, proveniente de Almería",
                            Features = "Dimensiones del producto : 7 x 8 x 7 cm; 250 g\nFabricante : MERCOPHAL, S.L\n",
                            FingerPrint = -17,
                            Name = "Tomates",
                            Price = 1m
                        },
                        new
                        {
                            Product_code = 7,
                            Category = 1,
                            Description = "Lechuga trocadero de gran calidad, proveniente de Francia",
                            Features = "Dimensiones del producto : 24,5 x 17 x 9,5 cm; 380 g\nFabricante : Felixia\nInstrucciones de almacenaje : 6° C -8° C\n",
                            FingerPrint = 47,
                            Name = "Lechuga trocadero",
                            Price = 2m
                        },
                        new
                        {
                            Product_code = 8,
                            Category = 1,
                            Description = "Calabacín de gran calidad, proveniente de España",
                            Features = "Dimensiones del producto : 18,01 x 5 x 3,99 cm; 500 g\nFabricante : Eurobanan\nInstrucciones de almacenaje : 6° C -8° C\n",
                            FingerPrint = 11,
                            Name = "Calabacín",
                            Price = 1m
                        },
                        new
                        {
                            Product_code = 9,
                            Category = 1,
                            Description = "Platanos de gran calidad, provenientes de Canarias",
                            Features = "Dimensiones del producto : 24 x 20 x 8 cm; 1,2 kg\nFabricante : ARC-EUROBANAN, S.L.\nConsumir preferiblemente en 2-3 días\n",
                            FingerPrint = 41,
                            Name = "Plátano de canarias",
                            Price = 2m
                        },
                        new
                        {
                            Product_code = 10,
                            Category = 1,
                            Description = "Melón de gran calidad, proveniente de Canarias",
                            Features = "Dimensiones del producto : 5,99 x 5 x 3,99 cm; 1,25 kg\nFabricante : Felixia\nInstrucciones de almacenaje : 10° C -12° C\n",
                            FingerPrint = 23,
                            Name = "Melón Cantaloup",
                            Price = 7m
                        });
                });

            modelBuilder.Entity("Backend.Database.SportProductEntity", b =>
                {
                    b.HasBaseType("Backend.Database.ProductEntity");

                    b.HasDiscriminator().HasValue("SportProductEntity");

                    b.HasData(
                        new
                        {
                            Product_code = 1,
                            Category = 2,
                            Description = "Zapatillas Nike Court Vision color blanco y verde, inspirado en el baloncesto de los 80Nike Court Vision Mid reúne el rétro del parquet y la comodidad moderna, con materiales reciclados para al menos el 20% de su peso. La suela tiene piezas en Nike Grind, mientras que el Tomaia testurizado en cuero sintético mantiene el aspecto clásico que le gusta tanto.",
                            Features = "Dimensiones del producto : 34 x 23 x 12 cm; 500 g\nMaterial de la suelaCaucho\nAltura de ejeAnkle Strap\nMaterial exteriorSintético\nMaterial internoSynthetic",
                            FingerPrint = 23,
                            Name = "Zapatillas Nike",
                            Price = 90m
                        },
                        new
                        {
                            Product_code = 2,
                            Category = 2,
                            Description = "Raqueta de espuma suave con protector integrado para mayor durabilidad, mayor potencia y menos vibraciones. La raqueta tiene un cuadro de carbono. Es la elección perfecta para los jóvenes",
                            Features = "Dimensiones del producto : 45 x 22 x 4 cm; 200 g\nMaterial : Grafito\nMaterial del marco : Carbono\nMaterial de la varilla : Fibra de carbono\n",
                            FingerPrint = -16,
                            Name = "Raqueta pádel",
                            Price = 80m
                        },
                        new
                        {
                            Product_code = 3,
                            Category = 2,
                            Description = "con la bolsa de FITGRIFF puede esperar una bolsa multiusos moderna y bien pensada: súper adecuada como bolsa de entrenamiento, bolsa de viaje, bolsa de baño",
                            Features = "Dimensiones del producto : 48 x 26 x 25 cm; 700 g\nFabricante : Fitgriff\nMaterial: 100% poliéster\n",
                            FingerPrint = -6,
                            Name = "Bolsa de gimnasio",
                            Price = 23m
                        },
                        new
                        {
                            Product_code = 4,
                            Category = 2,
                            Description = " el balón de fútbol está hecho de cuero de PVC suave y cosido con máquinas exquisitas para proporcionar una sensación de mano suave y equilibrada,resistente al desgaste y duradero. Revestimiento a prueba de explosiones",
                            Features = "Dimensiones del producto : 27 x 13,7 x 12 cm; 540 g\nMaterial : Cuero\nMarca : Aipwerer\n",
                            FingerPrint = -20,
                            Name = "Balón fútbol",
                            Price = 30m
                        },
                        new
                        {
                            Product_code = 5,
                            Category = 2,
                            Description = "Tejido de malla suave y confortable, cómodo y transpirable la camiseta deportiva tiene un corte holgado y es cómoda de llevar. Confeccionada con un tejido transpirable y que absorbe la humedad, absorbe el sudor y se seca rápidamente",
                            Features = "Dimensiones del producto : 15 x 10 x 1 cm; 300 g\nMaterial : dry-fit 100% poliéster \nMarca : Herbalife\n",
                            FingerPrint = -14,
                            Name = "Camiseta de deporte",
                            Price = 25m
                        });
                });

            modelBuilder.Entity("Backend.Database.TechnoProductEntity", b =>
                {
                    b.HasBaseType("Backend.Database.ProductEntity");

                    b.HasDiscriminator().HasValue("TechnoProductEntity");

                    b.HasData(
                        new
                        {
                            Product_code = 11,
                            Category = 0,
                            Description = "De tamaño mediano, fácil de agarrar para la mayoría de las personas, el peso ultraligero es de solo 75 gramos, diseño de panal ergonómico, fácil de agarrar y operar en juegos y oficinas",
                            Features = "Dimensiones del producto : 12,6 x 6,3 x 4 cm; 105 g\nFabricante : DIERYA\nSistema operativo: Windows 7/10\n",
                            FingerPrint = 25,
                            Name = "Ratón gaming",
                            Price = 32m
                        },
                        new
                        {
                            Product_code = 12,
                            Category = 0,
                            Description = "Teclado ultra responsivo + silencioso. disfrute de tiempos de respuesta rapidísimos con la tecnología inalámbrica de 2,4 ghz. el keyz tungsten ofrece una respuesta mucho más rápida y precisa que la mayoría de los teclados inalámbricos para juegos del mercado",
                            Features = "Dimensiones del producto : 25,4 x 5,08 x 6,86 cm; 800 g\nFabricante : AXS\nSistema operativo: Windows\n",
                            FingerPrint = -15,
                            Name = "Teclado gaming",
                            Price = 42m
                        },
                        new
                        {
                            Product_code = 13,
                            Category = 0,
                            Description = "el monitor de 24 pulgadas adopta una nueva generación de pantalla VA, que cubre el 99 % de la gama de colores SRGB. Por lo tanto, el monitor de la computadora puede restaurar al 100% los colores reales y presentar detalles vívidos. Además, el amplio ángulo de visión de 178° de este monitor de PC le permite disfrutar de imágenes claras, nítidas y delicadas desde cualquier ángulo.",
                            Features = "Dimensiones del producto : 42,32 x 54,2 x 18,11 cm; 3,63 kg\nFabricante : KOORUI\nInterfaz del hardware: VGA, HDMI\n",
                            FingerPrint = 10,
                            Name = "Monitor",
                            Price = 202m
                        },
                        new
                        {
                            Product_code = 14,
                            Category = 0,
                            Description = "El ventilador Aura II ha sido fabricado con el exclusivo y reconocido sistema de rodamientos de alta tecnología Tacens Fluxus II (10-12-12dB). Equipado a su vez con un cableado negro de alta calidad, que aumenta la protección y mejora la apariencia de este ventilador",
                            Features = "Dimensiones del producto : 35 x 3 x 15,01 cm; 98,5 g\nFabricante : ‎Tacens Spain\nDescripción de la batería: 12VDC\n",
                            FingerPrint = -10,
                            Name = "Ventilador ordenador",
                            Price = 7m
                        },
                        new
                        {
                            Product_code = 15,
                            Category = 0,
                            Description = "hecho de telas de felpa de alta calidad. Relleno de plumas de algodón PP en este peluche de pingüino totalmente vestido. El interior de alta calidad es realmente cómodo de sostener y soporta cualquier posición del cuerpo descansada a su alrededor.",
                            Features = "Dimensiones del producto : ‎6 x 5 x 12 cm; 140 g\nMaterial : ‎Nailon\nMarca: Generic\n",
                            FingerPrint = 41,
                            Name = "Peluche pingüino",
                            Price = 12m
                        });
                });

            modelBuilder.Entity("Backend.Database.GalleryEntity", b =>
                {
                    b.HasOne("Backend.Database.ProductEntity", "Product")
                        .WithMany("Gallery")
                        .HasForeignKey("Product_code");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Database.ListProduct", b =>
                {
                    b.HasOne("Backend.Database.ListEntity", "List")
                        .WithMany("listProducts")
                        .HasForeignKey("List_code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Database.ProductEntity", "Product")
                        .WithMany("ListProducts")
                        .HasForeignKey("Product_code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Database.GiftListEntity", b =>
                {
                    b.HasOne("Backend.Database.ClientEntity", "Client")
                        .WithOne("GiftList")
                        .HasForeignKey("Backend.Database.GiftListEntity", "ClientEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Backend.Database.LaterListEntity", b =>
                {
                    b.HasOne("Backend.Database.ClientEntity", "Client")
                        .WithOne("LaterList")
                        .HasForeignKey("Backend.Database.LaterListEntity", "ClientEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Backend.Database.ShoppingCartEntity", b =>
                {
                    b.HasOne("Backend.Database.ClientEntity", "Client")
                        .WithOne("ShoppingCart")
                        .HasForeignKey("Backend.Database.ShoppingCartEntity", "ClientEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Backend.Database.WishListEntity", b =>
                {
                    b.HasOne("Backend.Database.ClientEntity", "Client")
                        .WithOne("WishList")
                        .HasForeignKey("Backend.Database.WishListEntity", "ClientEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Backend.Database.ListEntity", b =>
                {
                    b.Navigation("listProducts");
                });

            modelBuilder.Entity("Backend.Database.ProductEntity", b =>
                {
                    b.Navigation("Gallery");

                    b.Navigation("ListProducts");
                });

            modelBuilder.Entity("Backend.Database.ClientEntity", b =>
                {
                    b.Navigation("GiftList")
                        .IsRequired();

                    b.Navigation("LaterList")
                        .IsRequired();

                    b.Navigation("ShoppingCart")
                        .IsRequired();

                    b.Navigation("WishList")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
